# Generated by Django 5.2.17 on 2026-09-13 02:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_id', models.BigIntegerField()),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(blank=True, max_length=30)),
                ('conclusion', models.CharField(blank=True, max_length=30)),
                ('raw_data', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('github_organization', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('template_repository', models.CharField(max_length=100)),
                ('due_at', models.DateTimeField()),
                ('late_penalty', models.IntegerField(default=-2)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('provisioning', 'Provisioning'), ('active', 'Active'), ('closed', 'Closed')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_assignments', to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='assignments.course')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(default=dict)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='assignments.assignment')),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generated_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_username', models.CharField(max_length=100)),
                ('display_name', models.CharField(blank=True, max_length=200)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='assignments.course')),
            ],
            options={
                'ordering': ['github_username'],
            },
        ),
        migrations.CreateModel(
            name='StudentRepository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repository_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('created', 'Created'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_repositories', to='assignments.assignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repositories', to='assignments.student')),
            ],
            options={
                'ordering': ['student__github_username'],
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=200)),
                ('score_text', models.CharField(max_length=100)),
                ('earned', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('maximum', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('workflow_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='assignments.workflowjob')),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_id', models.BigIntegerField()),
                ('created_at', models.DateTimeField()),
                ('status', models.CharField(blank=True, max_length=30)),
                ('conclusion', models.CharField(blank=True, max_length=30)),
                ('raw_data', models.JSONField(default=dict)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_runs', to='assignments.studentrepository')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='workflowjob',
            name='workflow_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='assignments.workflowrun'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='unique_course_owner_name'),
        ),
        migrations.AddConstraint(
            model_name='assignment',
            constraint=models.UniqueConstraint(fields=('course', 'name'), name='unique_assignment_course_name'),
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(fields=('course', 'github_username'), name='unique_student_course_username'),
        ),
        migrations.AddConstraint(
            model_name='studentrepository',
            constraint=models.UniqueConstraint(fields=('assignment', 'student'), name='unique_assignment_student_repository'),
        ),
        migrations.AddConstraint(
            model_name='studentrepository',
            constraint=models.UniqueConstraint(fields=('assignment', 'repository_name'), name='unique_assignment_repository_name'),
        ),
        migrations.AddConstraint(
            model_name='score',
            constraint=models.UniqueConstraint(fields=('workflow_job', 'test_name'), name='unique_workflow_job_test_score'),
        ),
        migrations.AddConstraint(
            model_name='workflowrun',
            constraint=models.UniqueConstraint(fields=('repository', 'github_id'), name='unique_repository_workflow_run'),
        ),
        migrations.AddConstraint(
            model_name='workflowjob',
            constraint=models.UniqueConstraint(fields=('workflow_run', 'github_id'), name='unique_workflow_run_job'),
        ),
    ]
